(define* (hello-dove)
	(display "hello \"from dove")
)

(define tex-star (rl/load-texture "star.png"))

(define white (colr-mk 255 255 255))
(define red (colr-mk 255 0 0))
(define* (tex-rect tex)
	(fvec4-mk 0 0 (rltex.width tex) (rltex.height tex))
)

(define* (update)
	(let 
		((height 20) ( w 120 ) ( h 60 ))
		(let ((draw-rct (lambda (colr) (rl/draw-rectangle 20 height w h colr) (+ h 20))))
			(let ((push-rct (lambda (colr) (set! height (+ height (draw-rct colr))))))
				(push-rct red)
				(push-rct (colr-mk 255 0 0))
				(push-rct (colr-mk 255 255 0))
				(push-rct (colr-mk 255 0 255))
			)
		)
	)
	(rl/draw-texture-ex tex-star (tex-rect tex-star) (fvec4-mk 60 60 60 60) (fvec2-mk 0 0) 0 white)
)
