(define* (hello-dove)
	(display "hello \"from dove")
)

(define tex-star (rl/load-texture "star.png"))

(define white (colr-mk 255 0 255))
(define red (colr-mk 255 255 0))
(define* (tex-rect tex)
	(fvec4-mk 0 0 (rl/tex2d.w tex) (rl/tex2d.h tex))
)

(define* (update)
	(let 
		((height 20) ( w 120 ) ( h 60 ))
		(let ((draw-rct (lambda (colr) (rl/draw-rectangle (fvec4-mk 20 height w h) colr) (+ h 20))))
			(let ((push-rct (lambda (colr) (set! height (+ height (draw-rct colr))))))
				(push-rct red)
				(push-rct (colr-mk 255 0 0))
				(push-rct white)
				(push-rct red)
				(push-rct red)
				(push-rct red)
			)
		)
		(rl/draw-rectangle (fvec4-mk 80 80 120 120) white)
	)
	(rl/draw-texture tex-star (tex-rect tex-star) (fvec4-mk 0 0 512 512) (fvec2-mk 0 0) 0 white)
)
